name: null
favicon: null
layout_spectrum: 0.045387099497020245
typography_spectrum: 0.5217628923710436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.12757306382991374
  lightness: 0.0673223389312625
  saturation: 0.5790879805572331
  rhythmicContrast: 0.2566272832918912
purpose: []
